# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1da071741fb6211a15996365da30b156e4a1bfe7ae5da7ac33a815ca7be8f4861a1d6aaefd2609739b5f033667f4f7138afa1edf6d1ba40b4325eab074cee03e

test:
  secret_key_base: 298fc54aaa7c067c2feb82f1e9c4655ab836406a8325d4adc057fcf7959a957a4d4c0f1d80550d2f49c78b1011db5fca4bf4376dfc50ba92fcc4e48452b4d053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
